import Head from "next/head";

import { Kumbh_Sans } from "@next/font/google";

import styles from "./Home.module.scss";
const kumbhSans = Kumbh_Sans({ subsets: ["latin"], weight: ["400", "700"] });

import { useContext, useState } from "react";

import { Header, Main, LightBox } from "components/Home";

import { BasketContext } from "@/context/BasketContext";

export const Home = () => {
    const [isMenuMobileOpen, setIsMenuMobileOpen] = useState(false);

    const { isZoomed } = useContext(BasketContext);

    function handleIsMenuMobileOpen() {
        setIsMenuMobileOpen(prevValue => !prevValue);
    }

    return (
        <div
            className={`${kumbhSans.className} ${styles.home_container} ${
                isZoomed && styles.home_container_background_zoom
            } ${isMenuMobileOpen && styles.home_container_background_mobile} `}
        >
            <Head>
                <title>Frontend Mentor | E-commerce product page</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/images/favicon-32x32.png" />
            </Head>

            <Header
                onMenuMobile={handleIsMenuMobileOpen}
                isMenuMobileOpen={isMenuMobileOpen}
            />

            <Main />

            {isZoomed && <LightBox />}
        </div>
    );
};
export { Header };
